name: SyncParatranz
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
jobs:
  SyncParatranz:
    name: "Downlaod Paratranz Artifacts"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PARAZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
      PARAZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'

      - uses: snok/install-poetry@v1.4.1

      - name: Cache Poetry Env
        uses: actions/cache@v4.2.0
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: python
          openapi-file: .github/workflows/paratranz-openapi.json
          output-dir: /tmp/openapi

      - name: "Instal Python Deps"
        run: poetry install

      - run: |
          just sync import

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: 'sync paratranz by github action'


  # paratranz2release:
  #   name: "Release Based on paratranz"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: action/checkout@v4
